# Generated by Django 3.1 on 2020-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
