# Generated by Django 3.1 on 2020-11-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_paciente_fechanacimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['-id']},
        ),
    ]
