# Generated by Django 3.1 on 2020-11-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_auto_20201117_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipoTerapia',
            field=models.CharField(blank=True, choices=[('Isapre', 'Isapre'), ('Fonasa', 'Fonasa'), ('Bajo Costo', 'Bajo Costo')], max_length=30, null=True),
        ),
    ]
