# Generated by Django 3.1 on 2020-11-25 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_auto_20201118_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='tipoTerapia',
            new_name='prevision',
        ),
    ]
