# Generated by Django 3.1 on 2021-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20201124_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='captacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivoConsulta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
