# Generated by Django 3.1 on 2021-03-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_auto_20210304_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='pagoDerivacion',
            field=models.BooleanField(default=False),
        ),
    ]
