# Generated by Django 3.1 on 2021-03-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_paciente_pagoderivacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='ocupacionProfecion',
        ),
    ]
