# Generated by Django 3.1 on 2021-03-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_paciente_valorsesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='prevision',
            field=models.CharField(blank=True, choices=[('Isapre', 'Isapre'), ('Fonasa', 'Fonasa'), ('Bajo Costo', 'Bajo Costo'), ('Pasantia', 'Pasantia')], max_length=30, null=True),
        ),
    ]
