# Generated by Django 3.1 on 2020-10-19 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTerapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTerapia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Terapia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('motivoConsulta', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoTerapia', models.CharField(blank=True, max_length=100, null=True)),
                ('captacion', models.CharField(blank=True, max_length=100, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('userAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistio', models.BooleanField(default=False)),
                ('fechaSesion', models.DateField()),
                ('terapia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terapia.terapia')),
            ],
        ),
    ]
