# Generated by Django 3.1 on 2020-10-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0002_auto_20201019_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapia',
            name='tipoTerapia',
            field=models.CharField(blank=True, choices=[('Isapre', 'Isapre'), ('Fonasa', 'Fonasa'), ('Bajo Costo', 'Bajo Costo')], max_length=30, null=True),
        ),
    ]
