# Generated by Django 3.1 on 2020-11-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0004_auto_20201026_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoTerapia',
        ),
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['-id']},
        ),
    ]
