# Generated by Django 3.1 on 2020-11-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0005_auto_20201117_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapia',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='terapia',
            name='tipoTerapia',
        ),
    ]
