# Generated by Django 3.1 on 2021-03-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0007_auto_20210304_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('Presencial', 'Presencial'), ('Online', 'Online')], max_length=30, null=True),
        ),
    ]
