# Generated by Django 3.1 on 2021-03-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapia', '0008_auto_20210306_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='emisionBoleta',
            field=models.BooleanField(default=False),
        ),
    ]
