# Generated by Django 3.1 on 2020-10-19 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilTerapeuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateTimeField(blank=True, null=True)),
                ('userAccount', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilTerapeuta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
