# Generated by Django 3.1 on 2020-11-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeuta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilterapeuta',
            name='tipoCuenta',
            field=models.CharField(choices=[('equipoInterno', 'equipoInterno'), ('equipoExterno', 'equipoExterno'), ('director', 'director'), ('pasante', 'pasante')], max_length=15, null=True),
        ),
    ]
